eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: tickets
          uri: lb://tickets
          predicates:
            - Path=/api/v1/tickets/**
        - id: notifications
          uri: lb://notifications
          predicates:
            - Path=/api/v1/notifications/**
        - id: authentications
          uri: lb://authentications
          predicates:
            - Path=/api/v1/auth/**




